package appgofig

import (
	"fmt"
	"os"
	"reflect"
	"strconv"
	"strings"
	"time"
)

// WriteToMarkdownFile creates a simple markdown table with information about the provided config inputs.
func WriteToMarkdownFile(targetConfig any, configDescriptions map[string]string, markdownFilePath string) error {
	if targetConfig == nil {
		return fmt.Errorf("unable to create config markdown file (%q): config is nil", markdownFilePath)
	}

	var sb strings.Builder

	currentTimeString := time.Now().Format(time.RFC3339)

	sb.WriteString("# Default Configuration Information\n")
	fmt.Fprintf(&sb, "*Generated %s*\n\n", currentTimeString)

	WriteMarkdownOverviewTable(targetConfig, configDescriptions, &sb)

	markdownFile, err := os.Create(markdownFilePath)
	if err != nil {
		return fmt.Errorf("unable to create config markdown file (%q): %w", markdownFilePath, err)
	}
	defer markdownFile.Close()

	if _, err := markdownFile.WriteString(sb.String()); err != nil {
		return fmt.Errorf("unable to write to config markdown file (%q): %w", markdownFilePath, err)
	}

	return nil
}

// WriteToYamlExampleFile creates an example yaml file with comments providing the description and applied defaults.
func WriteToYamlExampleFile(targetConfig any, configDescriptions map[string]string, yamlExampleFilePath string) error {
	if targetConfig == nil {
		return fmt.Errorf("unable to create example config yaml file (%q): config is nil", yamlExampleFilePath)
	}

	var sb strings.Builder

	currentTimeString := time.Now().Format(time.RFC3339)

	sb.WriteString("# Autogenerated config.yml.example file. Please provide your own values here.\n")
	fmt.Fprintf(&sb, "# Generated %s \n\n", currentTimeString)

	t := reflect.TypeOf(targetConfig).Elem()
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		fieldType := field.Type.Kind()
		yamlKey := field.Name

		defaultValue := field.Tag.Get("default")
		description := configDescriptions[field.Name]

		if fieldType == reflect.String {
			defaultValue = strconv.Quote(defaultValue)
		}

		required := " - optional"
		if isRequiredField(field) {
			required = " - required"
		}

		// Write Row
		fmt.Fprintf(&sb, "# %s [%s%s] - %s \n", yamlKey, fieldType.String(), required, description)
		fmt.Fprintf(&sb, "%s: %s\n\n", yamlKey, defaultValue)
	}

	configExampleYaml, err := os.Create(yamlExampleFilePath)
	if err != nil {
		return fmt.Errorf("unable to create example config yaml file (%q): %w", yamlExampleFilePath, err)
	}
	defer configExampleYaml.Close()

	if _, err := configExampleYaml.WriteString(sb.String()); err != nil {
		return fmt.Errorf("unable to write example config yaml to file (%q): %w", yamlExampleFilePath, err)
	}

	return nil
}

// WriteMarkdownOverviewTable will write a markdown table containing all availabel configuration information
// into the provided string builder
func WriteMarkdownOverviewTable(targetConfig any, configDescriptions map[string]string, sb *strings.Builder) {
	sb.WriteString("## Configuration Overview\n")
	sb.WriteString("This is an auto-generated overview of all configuration information\n")
	sb.WriteString("\n")
	sb.WriteString("| YAML Key | ENV Key | Type | Required | Default | Description |\n")
	sb.WriteString("|---|---|---|---|---|---|\n")

	t := reflect.TypeOf(targetConfig).Elem()
	for k := 0; k < t.NumField(); k++ {
		field := t.Field(k)
		fieldType := field.Type.Kind()
		yamlKey := field.Name
		envKey := strings.TrimSpace(field.Tag.Get("env"))
		if len(envKey) == 0 {
			envKey = field.Name
		}

		defaultValue := field.Tag.Get("default")
		description := configDescriptions[yamlKey]

		// mask default values
		if fieldType == reflect.String {
			defaultValue = fmt.Sprintf("`%s`", defaultValue)
		}

		required := "no"
		if isRequiredField(field) {
			required = "yes"
		}

		// Write Markdown row
		sb.WriteString("| " + yamlKey + " | `" + envKey + "` | " + fieldType.String() + " | " + required + " | " + defaultValue + " | " + description + " |\n")
	}
}
